version: "3.3"

services:
  web:
    build: ./
    command: uvicorn app.main:app --host "0.0.0.0" --port 8210
    ports:
      - 8210:8210
    depends_on:
      - redis
    restart:
      always

  redis:
    image: redis:latest
    restart:
      always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass b3e8oLd2t81
    volumes:
      - redis_data:/data

volumes:
  redis_data: